/**
 * The PDF Engine — builds a real, multi-page, multi-section branded PDF
 * client-side with jsPDF + jspdf-autotable (both already project
 * dependencies, same libraries `@/features/reporting`'s `exportToPdf` uses
 * for its single-table export). This is a genuine document: a cover page,
 * one or more content pages per section (heading + optional KPI summary +
 * optional data table + optional paragraphs), and a running header/footer
 * with page numbers stamped across every page once the full page count is
 * known. No network calls — everything happens in the browser.
 */

export interface PdfKpi {
  label: string;
  value: string;
}

export interface PdfTable {
  heading?: string;
  headers: string[];
  rows: (string | number)[][];
}

export interface PdfSection {
  heading: string;
  paragraphs?: string[];
  kpis?: PdfKpi[];
  tables?: PdfTable[];
}

export interface PdfReportDocument {
  title: string;
  subtitle: string;
  templateLabel: string;
  generatedByName: string;
  generatedAtLabel: string;
  orientation: "portrait" | "landscape";
  sections: PdfSection[];
}

const MARGIN = 16;
const BRAND = "Body Tracker";
const ACCENT_RGB: [number, number, number] = [63, 81, 181];
const MUTED_RGB: [number, number, number] = [120, 120, 128];

export async function generateReportPdf(doc: PdfReportDocument, filename: string): Promise<void> {
  const [{ jsPDF }, autoTableModule] = await Promise.all([
    import("jspdf"),
    import("jspdf-autotable"),
  ]);
  const autoTable = autoTableModule.default;

  const pdf = new jsPDF({
    orientation: doc.orientation,
    unit: "mm",
    format: "a4",
  });

  const pageWidth = pdf.internal.pageSize.getWidth();
  const pageHeight = pdf.internal.pageSize.getHeight();

  drawCoverPage(pdf, doc, pageWidth, pageHeight);

  for (const section of doc.sections) {
    pdf.addPage();
    drawSectionPage(pdf, autoTable, section, pageWidth);
  }

  stampHeaderAndFooter(pdf, doc, pageWidth, pageHeight);

  pdf.save(`${filename}.pdf`);
}

function drawCoverPage(
  pdf: import("jspdf").jsPDF,
  doc: PdfReportDocument,
  pageWidth: number,
  pageHeight: number,
): void {
  pdf.setFillColor(...ACCENT_RGB);
  pdf.rect(0, 0, pageWidth, 4, "F");

  pdf.setTextColor(...MUTED_RGB);
  pdf.setFontSize(11);
  pdf.text(BRAND, MARGIN, 24);

  pdf.setTextColor(30, 30, 34);
  pdf.setFontSize(26);
  const titleLines = pdf.splitTextToSize(doc.title, pageWidth - MARGIN * 2);
  pdf.text(titleLines, MARGIN, pageHeight / 2 - 20);

  pdf.setFontSize(13);
  pdf.setTextColor(...MUTED_RGB);
  pdf.text(doc.subtitle, MARGIN, pageHeight / 2 - 20 + titleLines.length * 10 + 6);

  const metaY = pageHeight - 40;
  pdf.setDrawColor(220, 220, 226);
  pdf.line(MARGIN, metaY - 8, pageWidth - MARGIN, metaY - 8);

  pdf.setFontSize(9.5);
  pdf.setTextColor(...MUTED_RGB);
  pdf.text(`Template: ${doc.templateLabel}`, MARGIN, metaY);
  pdf.text(`Generated by: ${doc.generatedByName}`, MARGIN, metaY + 6);
  pdf.text(`Generated: ${doc.generatedAtLabel}`, MARGIN, metaY + 12);
}

function drawSectionPage(
  pdf: import("jspdf").jsPDF,
  autoTable: (typeof import("jspdf-autotable"))["default"],
  section: PdfSection,
  pageWidth: number,
): void {
  let cursorY = 26;

  pdf.setTextColor(30, 30, 34);
  pdf.setFontSize(16);
  pdf.text(section.heading, MARGIN, cursorY);
  cursorY += 10;

  if (section.paragraphs?.length) {
    pdf.setFontSize(10);
    pdf.setTextColor(70, 70, 78);
    for (const paragraph of section.paragraphs) {
      const lines = pdf.splitTextToSize(paragraph, pageWidth - MARGIN * 2);
      pdf.text(lines, MARGIN, cursorY);
      cursorY += lines.length * 5 + 3;
    }
    cursorY += 2;
  }

  if (section.kpis?.length) {
    const colWidth = (pageWidth - MARGIN * 2) / 3;
    section.kpis.forEach((kpi, i) => {
      const col = i % 3;
      const row = Math.floor(i / 3);
      const x = MARGIN + col * colWidth;
      const y = cursorY + row * 18;
      pdf.setFontSize(8.5);
      pdf.setTextColor(...MUTED_RGB);
      pdf.text(kpi.label, x, y);
      pdf.setFontSize(13);
      pdf.setTextColor(30, 30, 34);
      pdf.text(kpi.value, x, y + 7);
    });
    const rowCount = Math.ceil(section.kpis.length / 3);
    cursorY += rowCount * 18 + 6;
  }

  for (const table of section.tables ?? []) {
    if (table.heading) {
      pdf.setFontSize(11);
      pdf.setTextColor(30, 30, 34);
      pdf.text(table.heading, MARGIN, cursorY);
      cursorY += 6;
    }
    autoTable(pdf, {
      startY: cursorY,
      margin: { left: MARGIN, right: MARGIN },
      head: [table.headers],
      body: table.rows,
      styles: { fontSize: 8.5, cellPadding: 3.5 },
      headStyles: { fillColor: ACCENT_RGB },
      alternateRowStyles: { fillColor: [246, 247, 251] },
    });
    const finalY = (pdf as unknown as { lastAutoTable?: { finalY: number } }).lastAutoTable?.finalY;
    cursorY = (finalY ?? cursorY) + 12;
  }
}

function stampHeaderAndFooter(
  pdf: import("jspdf").jsPDF,
  doc: PdfReportDocument,
  pageWidth: number,
  pageHeight: number,
): void {
  const totalPages = pdf.getNumberOfPages();
  for (let page = 2; page <= totalPages; page++) {
    pdf.setPage(page);

    pdf.setFontSize(8);
    pdf.setTextColor(...MUTED_RGB);
    pdf.text(doc.title, MARGIN, 10);
    pdf.setDrawColor(230, 230, 236);
    pdf.line(MARGIN, 13, pageWidth - MARGIN, 13);

    pdf.text(`${BRAND} · ${doc.generatedAtLabel}`, MARGIN, pageHeight - 8);
    pdf.text(`Page ${page - 1} of ${totalPages - 1}`, pageWidth - MARGIN, pageHeight - 8, {
      align: "right",
    });
  }
}
