"use client";

/**
 * Table view for the report library — wraps the existing generic
 * `DataTable<T>` rather than building a bespoke table. `DataTable` has no
 * `onRowClick` prop, so the Title cell itself is rendered as a clickable
 * element that opens the viewer.
 *
 * <ReportTable reports={data} />
 */

import { DataTable, type DataTableColumn } from "@/components/ui/data-table";
import { Avatar } from "@/components/ui/avatar";
import { cn } from "@/lib/utils";
import { useReportCenterStore } from "../store/report-center-store";
import { formatAbsoluteDate, formatFileSize } from "../lib/report-format";
import type { ReportRecord } from "../types";
import { ReportKindIcon } from "./report-kind-icon";
import { ReportStatusBadge, ReportTemplateBadge } from "./report-status-badge";

export function ReportTable({
  reports,
  className,
}: {
  reports: ReportRecord[];
  className?: string;
}) {
  const openViewer = useReportCenterStore((state) => state.openViewer);

  const columns: DataTableColumn<ReportRecord>[] = [
    {
      key: "title",
      header: "Title",
      render: (report) => (
        <button
          type="button"
          onClick={(event) => {
            event.stopPropagation();
            openViewer(report.id);
          }}
          className="group flex min-w-0 items-center gap-3 text-left"
        >
          <div className="bg-muted flex size-8 shrink-0 items-center justify-center rounded-md">
            <ReportKindIcon kind={report.kind} className="text-muted-foreground size-4" />
          </div>
          <div className="flex min-w-0 flex-col">
            <span
              className="text-foreground truncate text-sm font-medium group-hover:underline"
              title={report.title}
            >
              {report.title}
            </span>
            <span className="text-muted-foreground truncate text-xs">{report.dateRangeLabel}</span>
          </div>
        </button>
      ),
      sortable: true,
      sortValue: (report) => report.title,
    },
    {
      key: "template",
      header: "Template",
      render: (report) => <ReportTemplateBadge template={report.template} />,
      sortable: true,
      sortValue: (report) => report.template,
    },
    {
      key: "generatedBy",
      header: "Generated by",
      render: (report) => (
        <div className="flex items-center gap-2">
          <Avatar src={report.generatedBy.avatarSrc} fallback={report.generatedBy.name} size="sm" />
          <span className="text-foreground truncate text-sm">{report.generatedBy.name}</span>
        </div>
      ),
      sortable: true,
      sortValue: (report) => report.generatedBy.name,
    },
    {
      key: "createdAt",
      header: "Created",
      render: (report) => (
        <span className="text-muted-foreground text-sm">
          {formatAbsoluteDate(report.createdAt)}
        </span>
      ),
      sortable: true,
      sortValue: (report) => new Date(report.createdAt).getTime(),
    },
    {
      key: "fileSizeKb",
      header: "Size",
      render: (report) => (
        <span className="text-muted-foreground text-sm">{formatFileSize(report.fileSizeKb)}</span>
      ),
      sortable: true,
      sortValue: (report) => report.fileSizeKb,
      align: "right",
    },
    {
      key: "status",
      header: "Status",
      render: (report) => <ReportStatusBadge status={report.status} />,
      sortable: true,
      sortValue: (report) => report.status,
    },
  ];

  return (
    <DataTable
      data={reports}
      columns={columns}
      getRowId={(report) => report.id}
      searchable={false}
      emptyTitle="No reports match your search"
      emptyDescription="Try a different search term or clear your filters."
      className={cn(className)}
    />
  );
}
